definitions:
  models.Attendee:
    description: Attendee model represents a participant in an event.
    properties:
      email:
        type: string
      event_id:
        type: integer
      id:
        type: integer
      name:
        maxLength: 125
        minLength: 2
        type: string
    required:
    - email
    - name
    type: object
  models.Event:
    description: Represents an event with various attributes.
    properties:
      capacity:
        type: integer
      description:
        type: string
      end_at:
        type: string
      id:
        type: integer
      location:
        type: string
      start_at:
        type: string
      status:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
  description: This is the API specification for the Go Event Manager.
  title: Go Event Manager API Specification
  version: "0.1"
paths:
  /events:
    get:
      consumes:
      - application/json
      description: Get all events from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Event'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get all events
      tags:
      - events
    post:
      consumes:
      - application/json
      description: Create a new event in the database
      parameters:
      - description: Event details
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/models.Event'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Invalid request payload
          schema:
            type: string
      summary: Create a new event
      tags:
      - events
  /events/{event_id}/attendees:
    get:
      consumes:
      - application/json
      description: List all attendees that where registered in an event
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Attendee'
            type: array
        "400":
          description: Attendees not found
          schema:
            type: string
      summary: List all attendees for an event
      tags:
      - attendees
    post:
      consumes:
      - application/json
      description: Registers a new attendee to an existing event.
      parameters:
      - description: Attendee details
        in: body
        name: attendee
        required: true
        schema:
          $ref: '#/definitions/models.Attendee'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Attendee'
        "400":
          description: Invalid request payload
          schema:
            type: string
      summary: Register an attendee to an event
      tags:
      - attendees
  /events/{id}:
    delete:
      description: Delete an existing event by its ID
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Event deleted
          schema:
            type: string
        "404":
          description: Event not found
          schema:
            type: string
      summary: Delete an event
      tags:
      - events
    get:
      consumes:
      - application/json
      description: Retrieve a single event by its ID
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "404":
          description: Event not found
          schema:
            type: string
      summary: Get an event by ID
      tags:
      - events
    put:
      consumes:
      - application/json
      description: Update an existing event by its ID
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      - description: Event details to update
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/models.Event'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "404":
          description: Event not found
          schema:
            type: string
      summary: Update an event
      tags:
      - events
swagger: "2.0"
